/*
 * SmallObjectAllocator.h
 *
 *  Created on: 28 paü 2015
 *      Author: xxpowdaw
 */

#ifndef SMALLOBJECTALLOCATION_SMALLOBJECTALLOCATOR_H_
#define SMALLOBJECTALLOCATION_SMALLOBJECTALLOCATOR_H_





#endif /* SMALLOBJECTALLOCATION_SMALLOBJECTALLOCATOR_H_ */
